# Generated by Django 4.2.18 on 2025-02-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPS',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('cpu', models.PositiveIntegerField(verbose_name='CPU (количество ядер)')),
                ('ram', models.PositiveIntegerField(verbose_name='RAM (Мб)')),
                ('hdd', models.PositiveIntegerField(verbose_name='Объём диска (ГБ)')),
                ('status', models.CharField(choices=[('STARTED', 'started'), ('BLOCKED', 'blocked'), ('STOPPED', 'stopped')], default='stopped', max_length=15, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'VPS',
                'verbose_name_plural': 'VPS',
                'ordering': ('uid',),
            },
        ),
        migrations.AddConstraint(
            model_name='vps',
            constraint=models.CheckConstraint(check=models.Q(('ram__gte', 1024)), name='ram_minimum'),
        ),
    ]
