# Generated by Django 4.2.18 on 2025-02-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vps',
            name='cpu',
            field=models.PositiveIntegerField(verbose_name='CPU (Количество ядер)'),
        ),
    ]
